<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/01/04 18:50:29

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;port=8889;dbname=hrms',
  'username' => 'hrmsadmin',
  'password' => 'admin123',
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
